using System;
using System.IO;
using System.Text;

namespace EaWUnit.Core.Application
{
    internal static class AppUtility
    {
        internal static void PrintUsage()
        {
            Console.Out.WriteLine("Usage: dotnet eawunit.dll <TestMode> <inputFile> <outputDirectory>\n" +
                                  "       <TestMode>         WARNING or ERROR\n" +
                                  "       <inputFile>        Path to an existing test file generated by ModCheck.exe\n" +
                                  "       <outputDirectory>  Path to an existing directory.");
        }

        internal static void ParseArgs(string[] args)
        {
            if (args == null)
            {
                throw new ArgumentException("No arguments provided.");
            }

            if (args.Length != 3)
            {
                StringBuilder bldr = new StringBuilder();
                foreach (string s in args)
                {
                    bldr.AppendLine(s);
                }

                throw new ArgumentException($"Unexpected arguments: {bldr}");
            }

            if (args[0].Equals(TestMode.Warning.ToString(), StringComparison.InvariantCultureIgnoreCase))
            {
                ApplicationData.TestMode = TestMode.Warning;
            }
            else if (args[0].Equals(TestMode.Error.ToString(), StringComparison.InvariantCultureIgnoreCase))
            {
                ApplicationData.TestMode = TestMode.Error;
            }
            else
            {
                throw new ArgumentException($"Unexpected argument {args[0]}");
            }

            if (!File.Exists(args[1]))
            {
                throw new ArgumentException($"File does not exist: {args[1]}");
            }

            ApplicationData.ModCheckReportFilePath = args[1];

            if (!Directory.Exists(args[2]))
            {
                throw new ArgumentException($"Directory does not exist: {args[2]}");
            }

            ApplicationData.EaWUnitReportOutputPath = args[2];
        }
    }
}
